server:
  port: 8081

spring:
  application:
    name: mcp-learning-project
  
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:mcplearning
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson配置
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# MCP配置
mcp:
  server:
    host: localhost
    port: 3000
    timeout: 30000
  workflow:
    max-retries: 3
    retry-delay: 1000

# 日志配置
logging:
  level:
    com.example.mcp: DEBUG
    org.springframework.statemachine: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 